// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3qeLJFZSAAkSpMwlJqSKtBhHQn_ED_ns',
    appId: '1:400876988078:web:b7625783fc65a4e8acaf3f',
    messagingSenderId: '400876988078',
    projectId: 'proyectintegracion-24311',
    authDomain: 'proyectintegracion-24311.firebaseapp.com',
    storageBucket: 'proyectintegracion-24311.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCGiJi4cqCOGQ7cro3CXfEyxTgOKpjMgY',
    appId: '1:400876988078:android:117363ed3c210af9acaf3f',
    messagingSenderId: '400876988078',
    projectId: 'proyectintegracion-24311',
    storageBucket: 'proyectintegracion-24311.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzFdIe8jP6LUQ_d6-eykc2GU7JBgHuy_g',
    appId: '1:400876988078:ios:5c46c79b57456e7dacaf3f',
    messagingSenderId: '400876988078',
    projectId: 'proyectintegracion-24311',
    storageBucket: 'proyectintegracion-24311.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzFdIe8jP6LUQ_d6-eykc2GU7JBgHuy_g',
    appId: '1:400876988078:ios:4f306ead9143e9c9acaf3f',
    messagingSenderId: '400876988078',
    projectId: 'proyectintegracion-24311',
    storageBucket: 'proyectintegracion-24311.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
