// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDJoPt0ee59E3s7MQmj0qugRxhHnMVPOE',
    appId: '1:27365530123:web:cd8b5b95f29a170bdf850e',
    messagingSenderId: '27365530123',
    projectId: 'loginflutter-246d7',
    authDomain: 'loginflutter-246d7.firebaseapp.com',
    storageBucket: 'loginflutter-246d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSp0CeuwGnFjxC3eGBRLMlQewGcinlCXo',
    appId: '1:27365530123:android:d24e8d7e16e348d9df850e',
    messagingSenderId: '27365530123',
    projectId: 'loginflutter-246d7',
    storageBucket: 'loginflutter-246d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4pllWW6aD-4UdxPcIpzdTnOwJRgtSDvI',
    appId: '1:27365530123:ios:b839516d3a408515df850e',
    messagingSenderId: '27365530123',
    projectId: 'loginflutter-246d7',
    storageBucket: 'loginflutter-246d7.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4pllWW6aD-4UdxPcIpzdTnOwJRgtSDvI',
    appId: '1:27365530123:ios:d5234ca782ab62e9df850e',
    messagingSenderId: '27365530123',
    projectId: 'loginflutter-246d7',
    storageBucket: 'loginflutter-246d7.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
